#postgresql

services:
  postgresql:
    image: postgres:15
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: casadiny
      POSTGRES_PASSWORD: casadiny
      POSTGRES_DB: casadiny
    volumes:
      - ./_data/postgresql:/var/lib/postgresql/data # persist data
    ports:
      - "5432:5432"