version: '3.1'

services:
  postgresql:
  #postgresql 15
    image: postgres:15
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-store
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
  #redis
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  
  minio:
    #minio
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9010:9000"
      - "9011:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: test
      MINIO_ROOT_PASSWORD: testtest
    command: server --console-address ":9001" /data



volumes:
  postgres_data:
  minio_data:
  redis_data:
